id: P9F0AAF24
initial_creation_type: input
source_metadata:
  Title: Pañcaśatikā prajñāpāramitā
  Editor: Xuezhu Li, Yoshimichi Fujita
  Publisher: China Tibetology Publishing House
  Place of Publication: Beijing, China
  Year: '2017'
  पञ्चशतिका प्रज्ञापारमिता:
    Text Version: Devanagari
    Input Personnel: Miroj Shakya
    Input Date: '2017'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:06:33.086806'
last_modified_at: '2022-03-08T17:06:33.086816'
